export const Actions={
    GET_USER:'GET_USER',
    GET_USER_SUCCESS:'GET_USER_SUCCESS',
    GET_USER_FAIL:'GET_USER_FAIL',
    DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
    SUBMIT_USER:'SUBMIT_USER'
}